# https://taskfile.dev
version: '3'

env:
  PROJECT_ID: hamster-sandbox-428309

tasks:
  auth:
    desc: Authenticate to gcloud
    cmds:
      - gcloud config set project $PROJECT_ID
      - gcloud auth login
      - gcloud auth application-default login
  
  fmt:
    desc: Formats code
    cmds:
      - tofu fmt -recursive

  kubeconfig:
    desc: Generate kubeconfig
    cmds:
      - gcloud components install gke-gcloud-auth-plugin
      - gcloud container clusters get-credentials test --region us-central1

  docs:
    desc: Generate module documentation
    cmds:
      - terraform-docs markdown module > README.md
